model: baseline
epochs: 25
batch_size: 16
lr: 0.0001
lr_warmup_epochs: 0
weight_decay: 0.0001
early_stopping_patience: 7
label_smoothing: 0.1

use_balanced_sampler: false
use_class_weights: true

use_aug_balanced_dataset: true
aug_target_count_per_class: 800
aug_focal_alpha_uniform: false
